"""Change description to JSONB in Incident

Revision ID: 8ca410b37664
Revises: fcacbee96f69
Create Date: 2025-05-13 10:50:45.151739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ca410b37664'
down_revision: Union[str, None] = 'fcacbee96f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'incidents',
        'description',
        type_=sa.dialects.postgresql.JSONB(),
        postgresql_using='description::jsonb'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'incidents',
        'description',
        type_=sa.Text(),
        postgresql_using='description::text'
    )
    # ### end Alembic commands ###
