"""add integrations column to projects

Revision ID: e45fee2b77af
Revises: cb78fde7783d
Create Date: 2025-05-05 00:42:15.462618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45fee2b77af'
down_revision = 'cb78fde7783d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('projects', sa.Column('integrations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'integrations')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ### 